/** ISO 3166-1 alpha-2 country list with Arabic & English names */
export interface Country {
  code: string;   // ISO 3166-1 alpha-2, lowercase (e.g. "sa")
  nameAr: string;
  nameEn: string;
}

export function getFlagUrl(code: string): string {
  return `https://flagcdn.com/w40/${code.toLowerCase()}.png`;
}

export const COUNTRIES: Country[] = [
  { code: 'af', nameAr: 'أفغانستان', nameEn: 'Afghanistan' },
  { code: 'al', nameAr: 'ألبانيا', nameEn: 'Albania' },
  { code: 'dz', nameAr: 'الجزائر', nameEn: 'Algeria' },
  { code: 'ad', nameAr: 'أندورا', nameEn: 'Andorra' },
  { code: 'ao', nameAr: 'أنغولا', nameEn: 'Angola' },
  { code: 'ag', nameAr: 'أنتيغوا وبربودا', nameEn: 'Antigua & Barbuda' },
  { code: 'ar', nameAr: 'الأرجنتين', nameEn: 'Argentina' },
  { code: 'am', nameAr: 'أرمينيا', nameEn: 'Armenia' },
  { code: 'au', nameAr: 'أستراليا', nameEn: 'Australia' },
  { code: 'at', nameAr: 'النمسا', nameEn: 'Austria' },
  { code: 'az', nameAr: 'أذربيجان', nameEn: 'Azerbaijan' },
  { code: 'bs', nameAr: 'جزر البهاما', nameEn: 'Bahamas' },
  { code: 'bh', nameAr: 'البحرين', nameEn: 'Bahrain' },
  { code: 'bd', nameAr: 'بنغلاديش', nameEn: 'Bangladesh' },
  { code: 'bb', nameAr: 'باربادوس', nameEn: 'Barbados' },
  { code: 'by', nameAr: 'بيلاروسيا', nameEn: 'Belarus' },
  { code: 'be', nameAr: 'بلجيكا', nameEn: 'Belgium' },
  { code: 'bz', nameAr: 'بليز', nameEn: 'Belize' },
  { code: 'bj', nameAr: 'بنين', nameEn: 'Benin' },
  { code: 'bt', nameAr: 'بوتان', nameEn: 'Bhutan' },
  { code: 'bo', nameAr: 'بوليفيا', nameEn: 'Bolivia' },
  { code: 'ba', nameAr: 'البوسنة والهرسك', nameEn: 'Bosnia & Herzegovina' },
  { code: 'bw', nameAr: 'بوتسوانا', nameEn: 'Botswana' },
  { code: 'br', nameAr: 'البرازيل', nameEn: 'Brazil' },
  { code: 'bn', nameAr: 'بروناي', nameEn: 'Brunei' },
  { code: 'bg', nameAr: 'بلغاريا', nameEn: 'Bulgaria' },
  { code: 'bf', nameAr: 'بوركينا فاسو', nameEn: 'Burkina Faso' },
  { code: 'bi', nameAr: 'بوروندي', nameEn: 'Burundi' },
  { code: 'cv', nameAr: 'الرأس الأخضر', nameEn: 'Cabo Verde' },
  { code: 'kh', nameAr: 'كمبوديا', nameEn: 'Cambodia' },
  { code: 'cm', nameAr: 'الكاميرون', nameEn: 'Cameroon' },
  { code: 'ca', nameAr: 'كندا', nameEn: 'Canada' },
  { code: 'cf', nameAr: 'جمهورية أفريقيا الوسطى', nameEn: 'Central African Republic' },
  { code: 'td', nameAr: 'تشاد', nameEn: 'Chad' },
  { code: 'cl', nameAr: 'تشيلي', nameEn: 'Chile' },
  { code: 'cn', nameAr: 'الصين', nameEn: 'China' },
  { code: 'co', nameAr: 'كولومبيا', nameEn: 'Colombia' },
  { code: 'km', nameAr: 'جزر القمر', nameEn: 'Comoros' },
  { code: 'cg', nameAr: 'الكونغو', nameEn: 'Congo' },
  { code: 'cd', nameAr: 'الكونغو الديمقراطية', nameEn: 'Congo (DRC)' },
  { code: 'cr', nameAr: 'كوستاريكا', nameEn: 'Costa Rica' },
  { code: 'ci', nameAr: 'ساحل العاج', nameEn: "Côte d'Ivoire" },
  { code: 'hr', nameAr: 'كرواتيا', nameEn: 'Croatia' },
  { code: 'cu', nameAr: 'كوبا', nameEn: 'Cuba' },
  { code: 'cy', nameAr: 'قبرص', nameEn: 'Cyprus' },
  { code: 'cz', nameAr: 'جمهورية التشيك', nameEn: 'Czech Republic' },
  { code: 'dk', nameAr: 'الدنمارك', nameEn: 'Denmark' },
  { code: 'dj', nameAr: 'جيبوتي', nameEn: 'Djibouti' },
  { code: 'dm', nameAr: 'دومينيكا', nameEn: 'Dominica' },
  { code: 'do', nameAr: 'جمهورية الدومينيكان', nameEn: 'Dominican Republic' },
  { code: 'ec', nameAr: 'الإكوادور', nameEn: 'Ecuador' },
  { code: 'eg', nameAr: 'مصر', nameEn: 'Egypt' },
  { code: 'sv', nameAr: 'السلفادور', nameEn: 'El Salvador' },
  { code: 'gq', nameAr: 'غينيا الاستوائية', nameEn: 'Equatorial Guinea' },
  { code: 'er', nameAr: 'إريتريا', nameEn: 'Eritrea' },
  { code: 'ee', nameAr: 'إستونيا', nameEn: 'Estonia' },
  { code: 'sz', nameAr: 'إسواتيني', nameEn: 'Eswatini' },
  { code: 'et', nameAr: 'إثيوبيا', nameEn: 'Ethiopia' },
  { code: 'fj', nameAr: 'فيجي', nameEn: 'Fiji' },
  { code: 'fi', nameAr: 'فنلندا', nameEn: 'Finland' },
  { code: 'fr', nameAr: 'فرنسا', nameEn: 'France' },
  { code: 'ga', nameAr: 'الغابون', nameEn: 'Gabon' },
  { code: 'gm', nameAr: 'غامبيا', nameEn: 'Gambia' },
  { code: 'ge', nameAr: 'جورجيا', nameEn: 'Georgia' },
  { code: 'de', nameAr: 'ألمانيا', nameEn: 'Germany' },
  { code: 'gh', nameAr: 'غانا', nameEn: 'Ghana' },
  { code: 'gr', nameAr: 'اليونان', nameEn: 'Greece' },
  { code: 'gd', nameAr: 'غرينادا', nameEn: 'Grenada' },
  { code: 'gt', nameAr: 'غواتيمالا', nameEn: 'Guatemala' },
  { code: 'gn', nameAr: 'غينيا', nameEn: 'Guinea' },
  { code: 'gw', nameAr: 'غينيا بيساو', nameEn: 'Guinea-Bissau' },
  { code: 'gy', nameAr: 'غيانا', nameEn: 'Guyana' },
  { code: 'ht', nameAr: 'هايتي', nameEn: 'Haiti' },
  { code: 'hn', nameAr: 'هندوراس', nameEn: 'Honduras' },
  { code: 'hu', nameAr: 'هنغاريا', nameEn: 'Hungary' },
  { code: 'is', nameAr: 'آيسلندا', nameEn: 'Iceland' },
  { code: 'in', nameAr: 'الهند', nameEn: 'India' },
  { code: 'id', nameAr: 'إندونيسيا', nameEn: 'Indonesia' },
  { code: 'ir', nameAr: 'إيران', nameEn: 'Iran' },
  { code: 'iq', nameAr: 'العراق', nameEn: 'Iraq' },
  { code: 'ie', nameAr: 'أيرلندا', nameEn: 'Ireland' },
  { code: 'il', nameAr: 'إسرائيل', nameEn: 'Israel' },
  { code: 'it', nameAr: 'إيطاليا', nameEn: 'Italy' },
  { code: 'jm', nameAr: 'جامايكا', nameEn: 'Jamaica' },
  { code: 'jp', nameAr: 'اليابان', nameEn: 'Japan' },
  { code: 'jo', nameAr: 'الأردن', nameEn: 'Jordan' },
  { code: 'kz', nameAr: 'كازاخستان', nameEn: 'Kazakhstan' },
  { code: 'ke', nameAr: 'كينيا', nameEn: 'Kenya' },
  { code: 'ki', nameAr: 'كيريباتي', nameEn: 'Kiribati' },
  { code: 'kw', nameAr: 'الكويت', nameEn: 'Kuwait' },
  { code: 'kg', nameAr: 'قرغيزستان', nameEn: 'Kyrgyzstan' },
  { code: 'la', nameAr: 'لاوس', nameEn: 'Laos' },
  { code: 'lv', nameAr: 'لاتفيا', nameEn: 'Latvia' },
  { code: 'lb', nameAr: 'لبنان', nameEn: 'Lebanon' },
  { code: 'ls', nameAr: 'ليسوتو', nameEn: 'Lesotho' },
  { code: 'lr', nameAr: 'ليبيريا', nameEn: 'Liberia' },
  { code: 'ly', nameAr: 'ليبيا', nameEn: 'Libya' },
  { code: 'li', nameAr: 'ليختنشتاين', nameEn: 'Liechtenstein' },
  { code: 'lt', nameAr: 'ليتوانيا', nameEn: 'Lithuania' },
  { code: 'lu', nameAr: 'لوكسمبورغ', nameEn: 'Luxembourg' },
  { code: 'mg', nameAr: 'مدغشقر', nameEn: 'Madagascar' },
  { code: 'mw', nameAr: 'ملاوي', nameEn: 'Malawi' },
  { code: 'my', nameAr: 'ماليزيا', nameEn: 'Malaysia' },
  { code: 'mv', nameAr: 'المالديف', nameEn: 'Maldives' },
  { code: 'ml', nameAr: 'مالي', nameEn: 'Mali' },
  { code: 'mt', nameAr: 'مالطا', nameEn: 'Malta' },
  { code: 'mh', nameAr: 'جزر مارشال', nameEn: 'Marshall Islands' },
  { code: 'mr', nameAr: 'موريتانيا', nameEn: 'Mauritania' },
  { code: 'mu', nameAr: 'موريشيوس', nameEn: 'Mauritius' },
  { code: 'mx', nameAr: 'المكسيك', nameEn: 'Mexico' },
  { code: 'fm', nameAr: 'ميكرونيزيا', nameEn: 'Micronesia' },
  { code: 'md', nameAr: 'مولدوفا', nameEn: 'Moldova' },
  { code: 'mc', nameAr: 'موناكو', nameEn: 'Monaco' },
  { code: 'mn', nameAr: 'منغوليا', nameEn: 'Mongolia' },
  { code: 'me', nameAr: 'الجبل الأسود', nameEn: 'Montenegro' },
  { code: 'ma', nameAr: 'المغرب', nameEn: 'Morocco' },
  { code: 'mz', nameAr: 'موزمبيق', nameEn: 'Mozambique' },
  { code: 'mm', nameAr: 'ميانمار', nameEn: 'Myanmar' },
  { code: 'na', nameAr: 'ناميبيا', nameEn: 'Namibia' },
  { code: 'nr', nameAr: 'ناورو', nameEn: 'Nauru' },
  { code: 'np', nameAr: 'نيبال', nameEn: 'Nepal' },
  { code: 'nl', nameAr: 'هولندا', nameEn: 'Netherlands' },
  { code: 'nz', nameAr: 'نيوزيلندا', nameEn: 'New Zealand' },
  { code: 'ni', nameAr: 'نيكاراغوا', nameEn: 'Nicaragua' },
  { code: 'ne', nameAr: 'النيجر', nameEn: 'Niger' },
  { code: 'ng', nameAr: 'نيجيريا', nameEn: 'Nigeria' },
  { code: 'kp', nameAr: 'كوريا الشمالية', nameEn: 'North Korea' },
  { code: 'mk', nameAr: 'مقدونيا الشمالية', nameEn: 'North Macedonia' },
  { code: 'no', nameAr: 'النرويج', nameEn: 'Norway' },
  { code: 'om', nameAr: 'عُمان', nameEn: 'Oman' },
  { code: 'pk', nameAr: 'باكستان', nameEn: 'Pakistan' },
  { code: 'pw', nameAr: 'بالاو', nameEn: 'Palau' },
  { code: 'pa', nameAr: 'بنما', nameEn: 'Panama' },
  { code: 'pg', nameAr: 'بابوا غينيا الجديدة', nameEn: 'Papua New Guinea' },
  { code: 'py', nameAr: 'باراغواي', nameEn: 'Paraguay' },
  { code: 'pe', nameAr: 'بيرو', nameEn: 'Peru' },
  { code: 'ph', nameAr: 'الفلبين', nameEn: 'Philippines' },
  { code: 'pl', nameAr: 'بولندا', nameEn: 'Poland' },
  { code: 'pt', nameAr: 'البرتغال', nameEn: 'Portugal' },
  { code: 'qa', nameAr: 'قطر', nameEn: 'Qatar' },
  { code: 'ro', nameAr: 'رومانيا', nameEn: 'Romania' },
  { code: 'ru', nameAr: 'روسيا', nameEn: 'Russia' },
  { code: 'rw', nameAr: 'رواندا', nameEn: 'Rwanda' },
  { code: 'kn', nameAr: 'سانت كيتس ونيفيس', nameEn: 'Saint Kitts & Nevis' },
  { code: 'lc', nameAr: 'سانت لوسيا', nameEn: 'Saint Lucia' },
  { code: 'vc', nameAr: 'سانت فنسنت', nameEn: 'Saint Vincent' },
  { code: 'ws', nameAr: 'ساموا', nameEn: 'Samoa' },
  { code: 'sm', nameAr: 'سان مارينو', nameEn: 'San Marino' },
  { code: 'st', nameAr: 'ساو تومي وبرينسيبي', nameEn: 'São Tomé & Príncipe' },
  { code: 'sa', nameAr: 'المملكة العربية السعودية', nameEn: 'Saudi Arabia' },
  { code: 'sn', nameAr: 'السنغال', nameEn: 'Senegal' },
  { code: 'rs', nameAr: 'صربيا', nameEn: 'Serbia' },
  { code: 'sc', nameAr: 'سيشل', nameEn: 'Seychelles' },
  { code: 'sl', nameAr: 'سيراليون', nameEn: 'Sierra Leone' },
  { code: 'sg', nameAr: 'سنغافورة', nameEn: 'Singapore' },
  { code: 'sk', nameAr: 'سلوفاكيا', nameEn: 'Slovakia' },
  { code: 'si', nameAr: 'سلوفينيا', nameEn: 'Slovenia' },
  { code: 'sb', nameAr: 'جزر سليمان', nameEn: 'Solomon Islands' },
  { code: 'so', nameAr: 'الصومال', nameEn: 'Somalia' },
  { code: 'za', nameAr: 'جنوب أفريقيا', nameEn: 'South Africa' },
  { code: 'ss', nameAr: 'جنوب السودان', nameEn: 'South Sudan' },
  { code: 'es', nameAr: 'إسبانيا', nameEn: 'Spain' },
  { code: 'lk', nameAr: 'سريلانكا', nameEn: 'Sri Lanka' },
  { code: 'sd', nameAr: 'السودان', nameEn: 'Sudan' },
  { code: 'sr', nameAr: 'سورينام', nameEn: 'Suriname' },
  { code: 'se', nameAr: 'السويد', nameEn: 'Sweden' },
  { code: 'ch', nameAr: 'سويسرا', nameEn: 'Switzerland' },
  { code: 'sy', nameAr: 'سوريا', nameEn: 'Syria' },
  { code: 'tw', nameAr: 'تايوان', nameEn: 'Taiwan' },
  { code: 'tj', nameAr: 'طاجيكستان', nameEn: 'Tajikistan' },
  { code: 'tz', nameAr: 'تنزانيا', nameEn: 'Tanzania' },
  { code: 'th', nameAr: 'تايلاند', nameEn: 'Thailand' },
  { code: 'tl', nameAr: 'تيمور الشرقية', nameEn: 'Timor-Leste' },
  { code: 'tg', nameAr: 'توغو', nameEn: 'Togo' },
  { code: 'to', nameAr: 'تونغا', nameEn: 'Tonga' },
  { code: 'tt', nameAr: 'ترينيداد وتوباغو', nameEn: 'Trinidad & Tobago' },
  { code: 'tn', nameAr: 'تونس', nameEn: 'Tunisia' },
  { code: 'tr', nameAr: 'تركيا', nameEn: 'Turkey' },
  { code: 'tm', nameAr: 'تركمانستان', nameEn: 'Turkmenistan' },
  { code: 'tv', nameAr: 'توفالو', nameEn: 'Tuvalu' },
  { code: 'ug', nameAr: 'أوغندا', nameEn: 'Uganda' },
  { code: 'ua', nameAr: 'أوكرانيا', nameEn: 'Ukraine' },
  { code: 'ae', nameAr: 'الإمارات العربية المتحدة', nameEn: 'United Arab Emirates' },
  { code: 'gb', nameAr: 'المملكة المتحدة', nameEn: 'United Kingdom' },
  { code: 'us', nameAr: 'الولايات المتحدة', nameEn: 'United States' },
  { code: 'uy', nameAr: 'أوروغواي', nameEn: 'Uruguay' },
  { code: 'uz', nameAr: 'أوزبكستان', nameEn: 'Uzbekistan' },
  { code: 'vu', nameAr: 'فانواتو', nameEn: 'Vanuatu' },
  { code: 've', nameAr: 'فنزويلا', nameEn: 'Venezuela' },
  { code: 'vn', nameAr: 'فيتنام', nameEn: 'Vietnam' },
  { code: 'ye', nameAr: 'اليمن', nameEn: 'Yemen' },
  { code: 'zm', nameAr: 'زامبيا', nameEn: 'Zambia' },
  { code: 'zw', nameAr: 'زيمبابوي', nameEn: 'Zimbabwe' },
].sort((a, b) => a.nameAr.localeCompare(b.nameAr, 'ar'));
