FROM node:20-alpine

# pnpm@9 is the latest stable version available on npm.
# We use --no-frozen-lockfile to avoid version-mismatch errors between
# the lockfile (generated by Replit's internal pnpm) and pnpm@9 on Render.
RUN npm install -g pnpm@9

WORKDIR /app

# Copy everything
COPY . .

# Install all deps — no frozen lockfile to avoid settings.autoInstallPeers mismatch
RUN pnpm install --no-frozen-lockfile --prod=false

# Build the API server (esbuild bundles all workspace deps into one file)
RUN pnpm --filter @workspace/api-server run build

# Build the admin dashboard with production-safe defaults
RUN BASE_PATH=/ PORT=3000 NODE_ENV=production \
    pnpm --filter @workspace/admin-dashboard run build

# Copy admin dashboard static files into api-server dist so express.static serves them
RUN mkdir -p artifacts/api-server/dist/public && \
    cp -r artifacts/admin-dashboard/dist/public/. artifacts/api-server/dist/public/

EXPOSE 10000

CMD ["sh", "-c", "pnpm --filter @workspace/db run push && exec node --enable-source-maps ./artifacts/api-server/dist/index.mjs"]
