import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import homeRouter from "./home";
import visasRouter from "./visas";
import visaApplicationsRouter from "./visaApplications";
import packagesRouter from "./packages";
import packageBookingsRouter from "./packageBookings";
import flightsRouter from "./flights";
import notificationsRouter from "./notifications";
import bannersRouter from "./banners";
import testimonialsRouter from "./testimonials";
import adminRouter from "./admin";
import visasScanRouter from "./visas-scan";
import storageRouter from "./storage";
import passportOcrRouter from "../modules/passport-ocr/passport-ocr.controller";
import validateFaceRouter from "./validateFace";
import settingsRouter from "./settings";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(homeRouter);
router.use(visasRouter);
router.use(visaApplicationsRouter);
router.use(packagesRouter);
router.use(packageBookingsRouter);
router.use(flightsRouter);
router.use(notificationsRouter);
router.use(bannersRouter);
router.use(testimonialsRouter);
router.use(adminRouter);
router.use(visasScanRouter);
router.use(storageRouter);
router.use(passportOcrRouter);
router.use(validateFaceRouter);
router.use(settingsRouter);

export default router;
