export * from "./generated/api";
// Type-only interfaces — exported only where not already covered by the zod schema exports above.
// Some names overlap (e.g. FinalizeUploadResponse, ScanPassportOcrBody); rely on zod infer<typeof X> for those.
export type {
  AdminDashboardSummary,
  Banner,
  BannerInput,
  BannerUpdate,
  CabinClass,
  EmployeeInput,
  EmployeeUpdate,
  ErrorResponse,
  FlightBooking,
  FlightBookingInput,
  FlightBookingStatus,
  FlightBookingStatusUpdate,
  FlightOffer,
  HealthStatus,
  HomeSummary,
  Invoice,
  InvoiceInput,
  InvoiceItem,
  InvoiceStatus,
  InvoiceUpdate,
  ItineraryDay,
  ListAllFlightBookingsParams,
  ListAllPackageBookingsParams,
  ListAllVisaApplicationsParams,
  ListPackagesParams,
  ListVisasParams,
  LoginInput,
  MessageResponse,
  Notification,
  NotificationInput,
  NotificationType,
  Package,
  PackageBooking,
  PackageBookingInput,
  PackageBookingStatus,
  PackageBookingStatusUpdate,
  PackageInput,
  PackageUpdate,
  PassportData,
  PassportOcrResponse,
  PassportOcrResponseMeta,
  PasswordReset,
  PasswordResetRequest,
  Passenger,
  PaymentInput,
  PaymentMethod,
  PaymentStatus,
  Payment,
  PaymentUpdate,
  ProfileCompletion,
  ProfileUpdate,
  RecentActivity,
  SearchFlightsParams,
  SignupInput,
  Testimonial,
  TestimonialInput,
  TestimonialUpdate,
  TripType,
  UploadUrlRequest,
  UploadUrlResponse,
  User,
  UserRole,
  Visa,
  VisaApplication,
  VisaApplicationInput,
  VisaApplicationStatus,
  VisaApplicationStatusUpdate,
  VisaRequirements,
  VisaType,
  VisaUpdate,
} from "./generated/types";
export * from './generated/api';
export * from './generated/types';
