// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dark-mode/MidnightGold.tsx": () => import("../components/mockups/dark-mode/MidnightGold.tsx"),
  "./components/mockups/dark-mode/ObsidianAmber.tsx": () => import("../components/mockups/dark-mode/ObsidianAmber.tsx"),
  "./components/mockups/dark-mode/RoyalVelvet.tsx": () => import("../components/mockups/dark-mode/RoyalVelvet.tsx")
};
